### ISSUE TITLE
Redon Assignment-5

### ISSUE THREAD

**Issue by nateredon** [nateredon/Assignment-5#1]
In assignment 5, I decided to make a violin plot looking at variability in gillnet panel depth by site. I attempted to minimize clutter, used the Viridis colorset, and followed some of Jeff Leek's guidelines. I ran out of time working on this but **really** want to fix the horrible yellow color used in the final figure.

**Comment by mdscheuerell** [comment]
Yellow color aside, this is a really great plot, Nate!

To eliminate the yellow here, I would modify [this line](https://github.com/nateredon/Assignment-5/blob/f1ded7e2353a0a28b23f52cbc14ecf33051ed177/figures/Redon_Assignment5.Rmd#L83) to be something like

`scale_fill_viridis_d(end = 0.8)`

because the yellow colors are at the end of the palette (ie, near 1 on a relative scale).
